### PR TITLE
Add CI/CD pipeline

### PR DESCRIPTION
**Pull request by kilea-chan**
This PR allows us to build the static hugo site directly within github and also deploys it onto the server defined in the HOST secret

Following secrets need to be added:
- USER_NAME: The ssh username to connect to the destination server
- SSH_KEY: The private ssh key to connect to the destination server
- KNOWN_HOSTS: The ssh hash of the destination server
- HOST: The address of the destination server

Please ping me before merge, so that I can add the secrets to this repo.

The pipeline is split into two files, one for building and one for deployment.
This has been done to keep things clean.
___
**Note:** This pipeline implementation requires that the site content and the rest of the site source are part of the same repository.
When we get around in splitting up content and source into different repos, I will go ahead and do the required changes to the pipeline.

### CODE REVIEW

**Comment by Ereshkigal01** [comment]
LGTM , but as mentioned in the previous comment this pipeline will be modified once the content and code is seperated so not merging right now. 
Will merge at once when the content is seperated.

**Review by Ereshkigal01 — CHANGES_REQUESTED** [review]
Looks good please ping me when the pipeline regarding content is added

**Comment by kilea-chan** [comment]
@Ereshkigal01 pipeline now fetches content from the content repo.
I shall go ahead and add the required secrets to the repo

**Review by Ereshkigal01 — APPROVED** [review]

**Comment by Ereshkigal01** [comment]
Looks good to be merged, thanks for the efforts.
If anything comes up an issue will be opened to mitigate the issue.

**Comment by Ereshkigal01** [comment]
Looks good to be merged. If any issues comes an issue ticket will be opened ti mitigate it.

**Pull request merged**
